name: Developer_Pull_Requests.yml

on:
  pull_request:
    branches:
      - 'main'

env:
  service_name: expense-frontend

jobs:
  check-bats-version:
    uses: MMR-46org/github-actions/.github/workflows/Developer_Pull_Requests.yml@main
    secrets: inherit