name: Release_Tags.yml

on:
  push:
    tags:
      - "*"

#env:
#  service_name: expense-frontend


jobs:
  check-bats-version:
    uses: MMR-46org/github-actions/.github/workflows/Release_Tags.yml@main
    secrets: inherit
    with:
      service_name: expense-frontend